name: Node CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16.x ]

    steps:
      - uses: actions/checkout@v1
        
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
          
      - name: Lint and coverage
        run: |
          bun i
          bun run lint
          bun run build
          bun run coverage && bunx codecov
        env:
          CI: true
          
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}